# Available ruby versions: http://rubies.travis-ci.org/

language: ruby

os:
  - linux
  - osx

rvm:
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2.8"
  - "2.3.5"
  - "2.4.2"
  - "ruby-head"
  - "jruby-9.0.5.0"
  - "jruby-9.1.9.0"
  - "jruby-head"

cache: bundler

script:
  - bundle exec rake test
  - bundle exec rake rubocop

branches:
  except:
    - "readme-edits"

before_install:
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

matrix:
  exclude:
    - os: osx
      rvm: "2.4.2"
  allow_failures:
    - rvm: 'ruby-head'

  # return results as soon as mandatory versions are done
  fast_finish: true

sudo: false
